
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package com.brutus.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 12;
  public static final int OR = 13;
  public static final int RPAREN = 8;
  public static final int THEN = 10;
  public static final int MAG = 17;
  public static final int PIU = 3;
  public static final int N = 5;
  public static final int UGUG = 20;
  public static final int IF = 9;
  public static final int LPAREN = 7;
  public static final int PV = 2;
  public static final int GR = 15;
  public static final int MENO = 4;
  public static final int GL = 14;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int MULT = 6;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int MIN = 16;
  public static final int BOOL = 23;
  public static final int MAGUG = 19;
  public static final int VAR = 22;
  public static final int MINUG = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PV",
  "PIU",
  "MENO",
  "N",
  "MULT",
  "LPAREN",
  "RPAREN",
  "IF",
  "THEN",
  "EQ",
  "AND",
  "OR",
  "GL",
  "GR",
  "MIN",
  "MAG",
  "MINUG",
  "MAGUG",
  "UGUG",
  "NUMBER",
  "VAR",
  "BOOL"
  };
}

